name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options: 
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source cod
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python: "3.12"
      - name: install dependnencies
        run: pip install -r requirments.txt
      - name: Run tests
        run: pytest -v
