name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Stop Chrome processes
        run: |
          pkill -f chrome || echo "No Chrome processes found"
      - name: Copy source code
        uses: actions/checkout@v3
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up ChromeDriver and fix user data directory
        run: |
          mkdir -p /tmp/chrome_user_data  # Створення тимчасової директорії для користувача
      - name: Run tests
        run: pytest -v
        env:
          CHROME_USER_DATA_DIR: /tmp/chrome_user_data  # Використання тимчасової директорії для кожного тесту
